/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PeekABook } from './PeekABook'

export { PeekABook__factory } from './factories/PeekABook__factory'
